### ISSUE TITLE
Vitasploit Gets stuck at including "include/FW_330_336/utils.js" vita 3.36

### ISSUE THREAD

**Issue by bollafa** [Hykem/vitasploit#3]
![ss 2015-06-02 at 06 47 42](https://cloud.githubusercontent.com/assets/5232762/7941493/fa4de238-0957-11e5-81e4-6b6ee2fac75a.png)
Hello, for some reason when I connect my vita to the python server, it gets stuck at loading utils,
I have included document.write("Hello!") to test if initMemoryHole runs but it doesnt get called
![ss 2015-06-02 at 06 47 42] (http://puu.sh/i9NCK/0d8ce027f6.png)
Thanks in advance!

**Comment by Hykem** [comment]
This should now be fixed on the latest commit. Thanks for reporting!
